
all:
	echo "You must use backup or restore to copy to the thumbdrive and from the thumbdrive respectively."


.PHONY:backup
backup:
	cp -r ~/Desktop/CFA/latex /Volumes/THUMBDRIVE/CFA


.PHONY:restore
restore:
	cp -r /Volumes/THUMBDRIVE/CFA/latex ~/Desktop/CFA
	
